name: debounced_autocomplete
description: A Flutter autocomplete widget built on top of RawAutocomplete with built-in debouncing to optimize API calls and reduce unnecessary requests while users type.
version: 1.3.1
homepage: https://github.com/venhdev/debounced_autocomplete
repository: https://github.com/venhdev/debounced_autocomplete
issue_tracker: https://github.com/venhdev/debounced_autocomplete/issues

environment:
  sdk: ^3.10.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - autocomplete
  - debounce
  - flutter
  - widget
funding:
  - https://github.com/sponsors/venhdev
example: example

flutter:
